
LOGIN_USERNAME_FIELD = '//*[@id="loginname"]'
LOGIN_PASSWORD_FIELD = '//*[@id="password"]'
LOGIN_BUTTON = '/html/body/div[1]/div/div/div/div[2]/div[1]/div/div/div/div/div/div/form/div[3]/button'
LOGIN_BUTTON2 = '/html/body/div[1]/div/div/div/div[2]/div[1]/div/div/div/div/div/div/form/button'
SMS_BUTTON = '/html/body/div[1]/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div[2]/a[1]'
LINK = '/html/body/div[1]/main/div/div/header/div[2]/nav/div[2]/div/ul/li[4]/a'
BUTTON = '/html/body/div[1]/main/div/div/main/div/form/div[1]/fieldset/div/button[2]'
Down = '/html/body/div[1]/main/div/div/main/div/div[1]/div/div[2]/a[1]'
USERNAME = '554570'
PASSWORD = 'Julia1968='